### PR TITLE
HTML-Tables

### PR DESCRIPTION
**Pull request by Smith-Steve**

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Yo dude! The code looks good, but please provide a screenshot of your output :grin:

**Comment by Smith-Steve** [comment]
image

**Comment by Smith-Steve** [comment]
Hi @codingcodymiller hope you're well. I can't re-push this one since I haven't made any changes to it. Should I just "merge" anyway? The photo is attached as requested.

Steve

**Review by codingcodymiller — APPROVED** [review]
Nicely done!!

**Pull request merged**
